### PR TITLE
Bump Helm versions

### PR DESCRIPTION
**Pull request by wwentland**
This upgrades helm 2/3 to the latest release.

### CODE REVIEW

**Comment by stefanprodan** [comment]
Can you also bump Helm v2 please?

**Comment by wwentland** [comment]
Sure

**Comment by stefanprodan** [comment]
You also need to update the ghost HR values to https://github.com/fluxcd/flux-get-started/blob/master/releases/ghost.yaml#L16

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @babilen5

**Pull request merged**
