### PR TITLE
Recursively search directory for yaml files

### LINKED ISSUE #16: Recursively search for HelmRelease files
Search the provided directory recursively for yaml files

### PR DESCRIPTION
**Pull request by aaron-trout**
Fixes #16

### CODE REVIEW

**Comment by aaron-trout** [comment]
Hmm the Github actions docs are a bit thin on the ground regarding inputs / outputs but in general this works, just need to get the testing fixed 😄

**Comment by aaron-trout** [comment]
@stefanprodan are you able to re-run the CI for this? Looks like a transient failure downloading some dependencies but I don't think I am allowed to re-run since the button is missing for me. Thanks!

```
Not installing Tiller due to 'client-only' flag having been set
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
/deps.sh: line 15: helmv3: command not found
The command '/bin/sh -c /deps.sh' returned a non-zero code: 127
```

**Comment by stefanprodan** [comment]
@aaron-trout I've rerun the tests, now it fails with not much details...

**Comment by aaron-trout** [comment]
ah, thanks. I was too impatient, I also did a `git rebase -f` to force it to re run 😋

**Comment by aaron-trout** [comment]
Hmm yes interesting, it is not even getting through all the `kubeval` part 🤔 

We saw an issue like this where the container just exits with no message when using https://github.com/marketplace/actions/dipshit-kubeval 

I wonder if it is some bug in GitHub actions / Kubeval itself. I will see if I can do some extra debugging...

**Comment by aaron-trout** [comment]
Ok so I think now either the actions config is wrong and the value for `numFilesTested` is not getting through, or the bash arithmetic syntax is not playing ball. Will look at this more tomorrow.

**Comment by stefanprodan** [comment]
@aaron-trout thanks for your efforts, bash can be a nightmare some times. Tomorrow I'm flying all day but in the weekend I'll be able to review the PR.

**Comment by aaron-trout** [comment]
@stefanprodan should be good for review now! I did a bit of rebasing to get rid of all the "AARGHHHH BASH, WHYYYY" commits 😆 

Also added an `if` line on the image push to stop that happening on PRs.

**Review by stefanprodan — APPROVED** [review]
LGTM

**Pull request merged**
